eureka:
  client:
    service-url:
      #注册中心的访问地址。
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  #是否将当前服务的 IP 注册到 Eureka Server。
  instance:
    prefer-ip-address: true
    #Eureka	Status 下打开的ip地址url
    #hostname: clietnName
spring:
  application:
    name: client